# -*- coding: utf-8 -*-
"""telecomchurn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcj0iwNARk5v6-RpTCOpg0HhkhJVbM84
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
import warnings
warnings.filterwarnings('ignore')
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

#load telecom_churn.csv
df = pd.read_csv('telecom_churn.csv')
#print firs 5 rows
df.head()

#Check for null values
df.isnull().sum()

#plot distributions of all the variables
df.hist(figsize=(25,25))
plt.show()

#display the number of rows
df.shape[0]

#check for multicollinearity
# Select only numeric columns before calculating correlation
correlation_matrix = df.select_dtypes(include=np.number).corr()
#make into heat map
sns.heatmap(correlation_matrix,annot=True)

#make area code string
df['area code'] = df['area code'].astype(str)

#build and train XGBoost model
xgb = XGBClassifier(random_state=42)
xgb.fit(x_train,y_train)

#make predictions on the test set
y_pred = xgb.predict(x_test)

#print accuracy
print(accuracy_score(y_test,y_pred))

#print confusion matrix
print(confusion_matrix(y_test,y_pred))

#print classification report
print(classification_report(y_test,y_pred))